


development:
  adapter: postgresql
  encoding: utf8
  database: desker_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: desker_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: desker_production
  pool: 5
  timeout: 5000
